[general]
token = "ODM1MjQzODk5MzYxNDI3NDc2.YIMnfw.BfF2fUsK9g7aDU1mmILNVD7Z2Pw"

[categories]
    [categories.0]
    categoryId = "835282323075235840"

    autoText = true
    autoTextPrefix = "temp"
    autoTextPosition = "bottom"

    autoVoice = true
    autoVoicePrefix = "Voice"
    autoVoiceSlots = 5
    autoVoiceChannelLimit = 13
    autoVoiceBitrate = 96000
    autoVoicePermissions = []
